import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export async function GET(request: Request) {
  try {
    const supabase = await createClient(request);
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const { searchParams } = new URL(request.url);
    const start = searchParams.get("start") || "2020-01-01";
    const end = searchParams.get("end") || `${new Date().getFullYear() + 1}-12-31`;

    const { data: tx } = await supabase.from("transactions")
      .select("amount, category, platform, period")
      .eq("user_id", user.id)
      .gte("period", start).lte("period", end)
      .order("period");

    const income = (tx || []).filter((t) => t.amount > 0);
    const fees = (tx || []).filter((t) => t.amount < 0 && t.category === "platform_fee");
    const expenses = (tx || []).filter((t) => t.amount < 0 && t.category !== "platform_fee");
    const grossReceipts = income.reduce((s, t) => s + t.amount, 0);
    const totalExpenses = fees.reduce((s, t) => s + Math.abs(t.amount), 0) + expenses.reduce((s, t) => s + Math.abs(t.amount), 0);

    // Generate TXF format (TurboTax compatible)
    const year = new Date().getFullYear();
    const lines = [
      `V048 ${year}`,
      `A 1 ${user.id?.slice(0, 10) || ""}`,
      `N ${user.email || ""}`,
      `D ${new Date().toISOString().slice(0, 10)}`,
      `$`,
      `TD`,
      `N916`,
      `^Schedule C — generated by Staxx`,
      ``,
      `# Gross receipts or sales`,
      `S 1 ${Math.round(grossReceipts)} ${year}1231`,
      ``,
      `# Total expenses`,
      `E ${Math.round(totalExpenses)}`,
      ``,
      `# Category breakdown`,
    ];

    const expByCat: Record<string, number> = {};
    for (const t of [...fees, ...expenses]) {
      expByCat[t.category] = (expByCat[t.category] || 0) + Math.abs(t.amount);
    }
    for (const [cat, amt] of Object.entries(expByCat)) {
      lines.push(`? ${cat.replace(/_/g, " ")}: $${Math.round(amt)}`);
    }

    lines.push(``, `# Gross receipts by platform`);
    const byPlat: Record<string, number> = {};
    for (const t of income) { byPlat[t.platform] = (byPlat[t.platform] || 0) + t.amount; }
    for (const [plat, amt] of Object.entries(byPlat)) {
      lines.push(`? ${plat}: $${Math.round(amt)}`);
    }

    lines.push(``, `? Generated by Staxx — review with CPA before filing`);

    const txf = lines.join("\n");

    return new NextResponse(txf, {
      headers: {
        "Content-Type": "text/plain",
        "Content-Disposition": `attachment; filename="staxx-turbotax-${year}.txf"`,
      },
    });
  } catch (error) {
    return NextResponse.json({ error: String(error) }, { status: 500 });
  }
}
