import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export async function GET(request: Request) {
  try {
    // Accept token via query param for new-tab opens
    const { searchParams } = new URL(request.url);
    const urlToken = searchParams.get("token") || "";
    const supabase = urlToken
      ? await createClient(new Request(request.url, { headers: { Authorization: `Bearer ${urlToken}` } }))
      : await createClient(request);
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const start = searchParams.get("start") || "2020-01-01";
    const end = searchParams.get("end") || `${new Date().getFullYear() + 1}-12-31`;

    const { data: tx } = await supabase.from("transactions")
      .select("amount, category, platform, period")
      .eq("user_id", user.id).gte("period", start).lte("period", end).order("period");

    const fmt = (n: number) => "$" + n.toLocaleString(undefined, { minimumFractionDigits: 2 });
    const income = (tx || []).filter((t) => t.amount > 0);
    const fees = (tx || []).filter((t) => t.amount < 0 && t.category === "platform_fee");
    const expenses = (tx || []).filter((t) => t.amount < 0 && t.category !== "platform_fee");
    const gross = income.reduce((s, t) => s + t.amount, 0);
    const totalFees = fees.reduce((s, t) => s + Math.abs(t.amount), 0);
    const totalExp = expenses.reduce((s, t) => s + Math.abs(t.amount), 0);
    const net = gross - totalFees - totalExp;

    const expByCat: Record<string, number> = {};
    for (const t of expenses) expByCat[t.category] = (expByCat[t.category] || 0) + Math.abs(t.amount);

    const byPlat: Record<string, number> = {};
    for (const t of income) byPlat[t.platform] = (byPlat[t.platform] || 0) + t.amount;

    const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Staxx — Schedule C Report</title>
<style>
  body { font-family: -apple-system, Inter, sans-serif; max-width: 640px; margin: 40px auto; padding: 0 20px; color: #1e1b4b; }
  h1 { font-size: 22px; margin-bottom: 4px; } .date { color: #888; font-size: 13px; margin-bottom: 24px; }
  .card { background: #f5f3ff; border-radius: 16px; padding: 20px; margin-bottom: 16px; }
  .row { display: flex; justify-content: space-between; padding: 8px 0; font-size: 15px; }
  .total { font-weight: 700; font-size: 18px; border-top: 2px solid #7c3aed; padding-top: 12px; margin-top: 8px; }
  .section { margin-top: 24px; } h2 { font-size: 16px; margin-bottom: 8px; }
  .bar { display: flex; align-items: center; gap: 8px; margin-bottom: 6px; font-size: 13px; }
  .bar-fill { height: 8px; border-radius: 4px; background: #7c3aed; }
  .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #eee; font-size: 11px; color: #999; }
  @media print { body { margin: 0; } .no-print { display: none; } }
</style></head><body>
<h1>Schedule C Report</h1>
<div class="date">${start} → ${end} · ${tx?.length || 0} transactions</div>
<div class="card">
  <div class="row"><span>Gross Receipts</span><span>${fmt(gross)}</span></div>
  <div class="row"><span>Platform Fees</span><span style="color:#f87171">−${fmt(totalFees)}</span></div>
  <div class="row"><span>Total Deductions</span><span style="color:#34d399">−${fmt(totalExp)}</span></div>
  <div class="row total"><span>Net Profit</span><span>${fmt(net)}</span></div>
</div>
${Object.keys(expByCat).length > 0 ? `<div class="section"><h2>Deduction Breakdown</h2>
${Object.entries(expByCat).sort(([,a],[,b])=>b-a).map(([cat,amt])=>`<div class="bar"><span style="width:100px;text-transform:capitalize;font-size:12px">${cat.replace(/_/g," ")}</span><div class="bar-fill" style="width:${Math.max(10,(amt/totalExp)*200)}px"></div><span>${fmt(amt)}</span></div>`).join("")}</div>`:""}
${Object.keys(byPlat).length > 0 ? `<div class="section"><h2>Income by Platform</h2>
${Object.entries(byPlat).sort(([,a],[,b])=>b-a).map(([plat,amt])=>`<div class="bar"><span style="width:100px;text-transform:capitalize;font-size:12px">${plat}</span><div class="bar-fill" style="width:${Math.max(10,(amt/gross)*200)}px"></div><span>${fmt(amt)}</span></div>`).join("")}</div>`:""}
<div class="footer">Generated by Staxx · This is tax-ready data, not tax advice. Review with a CPA before filing.</div>
<div class="no-print" style="text-align:center;margin-top:24px">
  <button onclick="window.print()" style="background:#7C3AED;color:#fff;border:none;padding:12px 32px;border-radius:12px;font-size:15px;font-weight:600;cursor:pointer">🖨️ Print / Save as PDF</button>
  <p style="color:#888;font-size:12px;margin-top:8px">Use your browser's "Save as PDF" option when printing</p>
</div>
</body></html>`;

    return new NextResponse(html, {
      headers: { "Content-Type": "text/html; charset=utf-8" },
    });
  } catch (error) {
    return NextResponse.json({ error: String(error) }, { status: 500 });
  }
}
