import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export async function GET(request: Request) {
  try {
    const supabase = await createClient(request);
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const { data: tx } = await supabase
      .from("transactions")
      .select("period, platform, category, amount")
      .eq("user_id", user.id)
      .order("period");

    if (!tx?.length) {
      return new NextResponse("No transactions found.", {
        headers: { "Content-Type": "text/csv", "Content-Disposition": "attachment; filename=staxx-empty.csv" },
      });
    }

    const lines: string[] = [];
    const fmt = (n: number) => n.toFixed(2);

    // Header
    lines.push("=== STACKS EXPORT ===");
    lines.push(`Exported: ${new Date().toISOString().slice(0, 10)}`);
    lines.push(`Total Transactions: ${tx.length}`);
    lines.push("");

    // Income section
    const income = tx.filter((t) => t.amount > 0);
    if (income.length > 0) {
      lines.push("--- INCOME ---");
      lines.push("Date,Platform,Category,Amount");
      let incomeTotal = 0;
      for (const t of income) {
        lines.push(`${t.period.slice(0, 10)},${t.platform},${t.category},${fmt(t.amount)}`);
        incomeTotal += t.amount;
      }
      lines.push(`TOTAL INCOME,,,${"$" + incomeTotal.toLocaleString(undefined, { minimumFractionDigits: 2 })}`);
      lines.push("");
    }

    // Platform fees section
    const fees = tx.filter((t) => t.category === "platform_fee");
    if (fees.length > 0) {
      lines.push("--- PLATFORM FEES ---");
      lines.push("Date,Platform,Category,Amount");
      let feesTotal = 0;
      for (const t of fees) {
        lines.push(`${t.period.slice(0, 10)},${t.platform},${t.category},${fmt(t.amount)}`);
        feesTotal += t.amount;
      }
      lines.push(`TOTAL FEES,,,${"$" + Math.abs(feesTotal).toLocaleString(undefined, { minimumFractionDigits: 2 })}`);
      lines.push("");
    }

    // Expenses section
    const expenses = tx.filter((t) => t.amount < 0 && t.category !== "platform_fee");
    if (expenses.length > 0) {
      lines.push("--- EXPENSES ---");
      lines.push("Date,Platform,Category,Amount");
      let expTotal = 0;
      // Group by category
      const byCat: Record<string, number> = {};
      for (const t of expenses) {
        byCat[t.category] = (byCat[t.category] || 0) + t.amount;
      }
      for (const [cat, amt] of Object.entries(byCat).sort(([, a], [, b]) => a - b)) {
        lines.push(`  ,,${cat},${fmt(amt)}`);
        expTotal += amt;
      }
      lines.push(`TOTAL EXPENSES,,,${"$" + Math.abs(expTotal).toLocaleString(undefined, { minimumFractionDigits: 2 })}`);
      lines.push("");
    }

    // Grand total
    const netProfit = tx.reduce((s, t) => s + t.amount, 0);
    lines.push("=== GRAND TOTAL ===");
    lines.push(`Gross Income: $${income.reduce((s, t) => s + t.amount, 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`);
    lines.push(`Platform Fees: -$${Math.abs(fees.reduce((s, t) => s + t.amount, 0)).toLocaleString(undefined, { minimumFractionDigits: 2 })}`);
    lines.push(`Expenses: -$${Math.abs(expenses.reduce((s, t) => s + t.amount, 0)).toLocaleString(undefined, { minimumFractionDigits: 2 })}`);
    lines.push(`NET PROFIT: $${netProfit.toLocaleString(undefined, { minimumFractionDigits: 2 })}`);
    lines.push("");
    lines.push("Generated by Staxx — stack smarter, create freer.");
    lines.push("This is tax-ready data, not tax advice. Review with a CPA.");

    const csv = lines.join("\n");

    return new NextResponse(csv, {
      headers: {
        "Content-Type": "text/csv",
        "Content-Disposition": `attachment; filename="staxx-export-${new Date().toISOString().slice(0, 10)}.csv"`,
      },
    });
  } catch (error) {
    return NextResponse.json({ error: String(error) }, { status: 500 });
  }
}
